total 1072
-rw-r--r--@ 1 AhmadRangeen  staff  508518 Jun 21 15:59 415_HW3.pdf
-rw-r--r--  1 AhmadRangeen  staff     159 Jun 21 15:59 CMakeLists.txt
-rw-r--r--  1 AhmadRangeen  staff    1074 Jun 21 15:59 LICENSE
-rw-r--r--  1 AhmadRangeen  staff       0 Jul  6 20:27 Makefile
-rw-r--r--  1 AhmadRangeen  staff      11 Jun 21 15:59 README.md
-rwxr-xr-x  1 AhmadRangeen  staff    8844 Jun 30 19:49 a.out
-rw-r--r--  1 AhmadRangeen  staff    4601 Jul  6 20:11 myshell.c
-rw-r--r--  1 AhmadRangeen  staff       4 Jun 21 15:59 readme.txt
